/** Все возможные ключи полей для подсказок администратора */
export const TOOLTIP_FIELD_KEYS = [
  { value: 'home.hero', label: 'Главная — приветственный блок' },
  { value: 'home.steps', label: 'Главная — как подать заявление' },
  { value: 'login.email', label: 'Вход — email' },
  { value: 'login.password', label: 'Вход — пароль' },
  { value: 'register.lastName', label: 'Регистрация — фамилия' },
  { value: 'register.firstName', label: 'Регистрация — имя' },
  { value: 'register.middleName', label: 'Регистрация — отчество' },
  { value: 'register.email', label: 'Регистрация — email' },
  { value: 'register.password', label: 'Регистрация — пароль' },
  { value: 'profile.lastName', label: 'Профиль — фамилия' },
  { value: 'profile.firstName', label: 'Профиль — имя' },
  { value: 'profile.middleName', label: 'Профиль — отчество' },
  { value: 'profile.group', label: 'Профиль — группа (только просмотр)' },
  { value: 'profile.faculty', label: 'Профиль — факультет (только просмотр)' },
  { value: 'profile.recordBook', label: 'Профиль — зачётная книжка' },
  { value: 'profile.studentCard', label: 'Профиль — студенческий билет' },
  { value: 'application.direction', label: 'Заявление — направление' },
  { value: 'application.level', label: 'Заявление — уровень достижения' },
  { value: 'application.title', label: 'Заявление — название' },
  { value: 'application.description', label: 'Заявление — описание' },
  { value: 'application.attachments', label: 'Заявление — вложения' },
  { value: 'application.score', label: 'Заявление — баллы' },
  { value: 'directions.list', label: 'Направления — список' },
  { value: 'regulations.document', label: 'Регламент — документ' },
  { value: 'regulations.section', label: 'Регламент — раздел' },
  { value: 'rating.table', label: 'Рейтинг — таблица' },
  { value: 'rating.place', label: 'Рейтинг — место' },
  { value: 'admin.users', label: 'Админ — пользователи' },
  { value: 'admin.faculties', label: 'Админ — факультеты' },
  { value: 'admin.groups', label: 'Админ — группы' },
  { value: 'admin.directions', label: 'Админ — направления ПГАС' },
  { value: 'admin.tooltips', label: 'Админ — подсказки' },
  { value: 'admin.applications', label: 'Админ — заявления' },
  { value: 'commission.regulations', label: 'Комиссия — регламент' },
  { value: 'commission.directions', label: 'Комиссия — направления' },
  { value: 'commission.review', label: 'Комиссия — рассмотрение заявления' },
];
