/** Все возможные ключи полей для подсказок администратора */
export const TOOLTIP_FIELD_KEYS = [
  { value: 'login.email', label: 'Вход — email' },
  { value: 'login.password', label: 'Вход — пароль' },
  { value: 'home.heroTitle', label: 'Главная — заголовок' },
  { value: 'home.deadline', label: 'Главная — дедлайн подачи' },
  { value: 'home.goToSystem', label: 'Главная — кнопка перехода в систему' },
  { value: 'home.goToDirections', label: 'Главная — кнопка перехода к направлениям' },
  { value: 'register.lastName', label: 'Регистрация — фамилия' },
  { value: 'register.firstName', label: 'Регистрация — имя' },
  { value: 'register.middleName', label: 'Регистрация — отчество' },
  { value: 'register.email', label: 'Регистрация — email' },
  { value: 'register.password', label: 'Регистрация — пароль' },
  { value: 'profile.lastName', label: 'Профиль — фамилия' },
  { value: 'profile.firstName', label: 'Профиль — имя' },
  { value: 'profile.middleName', label: 'Профиль — отчество' },
  { value: 'profile.group', label: 'Профиль — группа (только просмотр)' },
  { value: 'profile.faculty', label: 'Профиль — факультет (только просмотр)' },
  { value: 'profile.recordBook', label: 'Профиль — зачётная книжка' },
  { value: 'profile.studentCard', label: 'Профиль — студенческий билет' },
  { value: 'application.level', label: 'Заявление — уровень достижения' },
  { value: 'application.title', label: 'Заявление — название' },
  { value: 'application.description', label: 'Заявление — описание' },
  { value: 'application.attachments', label: 'Заявление — вложения' },
  { value: 'application.submit', label: 'Заявление — кнопка отправить' },
  { value: 'application.draft', label: 'Заявление — кнопка черновик' },
  { value: 'application.cancel', label: 'Заявление — кнопка отмена' },
];
